spring:
    application:
        name: webflux
    data:
        mongodb:
            host: 101.79.8.41
            port: 27018
            authentication-database: admin
            database: users
    sql:
        init:
            platform: mongo
            mode: always
logging:
    level:
        org:
            hibernate:
                SQL: debug
                type: trace
server:
  port: 8081