spring:
  application:
    name: api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.79.8.41:3307/turingdb
    username: root
    password: root
  sql:
    init:
      platform: mysql
      mode: always
      encoding: utf-8
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            "[non_contextual_creation]": true
        "[format_sql]": true
    show-sql: true
  #  open-in-view: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace
      springframework:
        security : DEBUG
        web : DEBUG
        data : DEBUG
        hibernate : DEBUG
        jpa : DEBUG
        jwt : DEBUG
        bezkoder : DEBUG
jwt:
  iss: turing.co.kr
  exp: 24*60*60*1000 # a day
  secret: turingturingturingturingturingturingturingturingturing
  refresh-token:
    exp: (24*60*60*1000)*7 # a week
server:
  port: 8081