spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ggundb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            "[non_contextual_creation]": true
        "[format_sql]": true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  iss: ggun.store
  exp: 24*60*60*1000
  secret: ggunggunggunggunggunggunggunggunggunggunggunggunggunggunggunggun
